pipeline:
    test:
        image: node:8
        commands:
            - npm install
            - npm run unit
            - npm run e2e:docker
        environment:
            - MONGODB_HOST=mongodb://mongodb:27017/passprotect
            - MONGODB_DATABASE=passprotect
            - HOST=test

    nodejs:
        image: plugins/docker
        repo: phoenix741/passprotect-server
        tags: develop
        dockerfile: Dockerfile.nodejs

    nginx:
        image: plugins/docker
        repo: phoenix741/passprotect-client
        tags: develop
        dockerfile: Dockerfile.nginx

services:
    selenium:
        image: selenium/standalone-chrome

    mongodb:
        image: mongo:3.6
