pipeline:
    test:
        image: node:8-alpine
        commands:
            - npm install
            - npm run e2e -- --config test/e2e/nightwatch.docker.conf.js

    nodejs:
        image: plugins/docker
        repo: phoenix741/passprotect-server
        tags: develop
        dockerfile: Dockerfile.nodejs

    nginx:
        image: plugins/docker
        repo: phoenix741/passprotect-client
        tags: develop
        dockerfile: Dockerfile.nginx

services:
    selenium:
        image: selenium/standalone-chrome

    mongodb:
        image: mongo:3.5
