pipeline:
    nodejs:
        image: plugins/docker
        repo: phoenix741/passprotect-server
        tags: develop
        dockerfile: Dockerfile.nodejs

    nginx:
        image: plugins/docker
        repo: phoenix741/passprotect-client
        tags: develop
        dockerfile: Dockerfile.nginx
