version: '2'
services:
    nodejs:
        build:
          context: ./
          dockerfile: Dockerfile.nodejs
        image: phoenix741/passprotect-server:1.0.0
        expose:
            - 3000
        links:
            - mongodb
        environment:
            - MONGODB_HOST=mongodb://mongodb:27017/passprotect
            - NODE_ENV=production
            - DEBUG=App:*
    nginx:
        build:
          context: ./
          dockerfile: Dockerfile.nginx
        image: phoenix741/passprotect-client:1.0.0
        links:
            - nodejs
        environment:
            - UPSTREAM_SERVER=nodejs
            - UPSTREAM_PORT=3000
        ports:
            - '8080:80'
    mongodb:
        image: mongo:3.3.9
        ports:
            - '27017:27017'
        volumes:
            - './mongodb:/data'
