version: '2'
services:
    nodejs:
        build:
          context: ./
          dockerfile: Dockerfile
        image: phoenix741/passprotect-server:develop
        ports:
            - 4000:4000
        links:
            - mongodb
        environment:
            - MONGODB_HOST=mongodb://mongodb:27017/passprotect
            - MONGODB_DATABASE=passprotect
            - NODE_ENV=production
            - DEBUG=App:*
    mongodb:
        image: mongo:4
        ports:
            - '27017:27017'
        volumes:
            - './mongodb:/data'
