FROM mhart/alpine-node:6.2.2
MAINTAINER Ulrich Van Den Hekke <ulrich.vdh@shadoware.org>

ENV MODE=prod
ENV NODE_ENV=production

WORKDIR /src

COPY package.json /src
RUN npm install && npm cache clean
COPY . /src

EXPOSE 3000
CMD ["npm", "start"]
