version: '2'
services:
    nodejs:
        build:
          context: ./
          dockerfile: Dockerfile.nodejs
        image: phoenix741/passprotect-server:develop
        expose:
            - 3000
        links:
            - mongodb
        environment:
            - MONGODB_HOST=mongodb://mongodb:27017/passprotect
            - MONGODB_DATABASE=passprotect
            - NODE_ENV=production
            - DEBUG=App:*
    mongodb:
        image: mongo:3.5
        ports:
            - '27017:27017'
        volumes:
            - './mongodb:/data'
