version: '2'
services:
    nodejs:
        build:
          context: ./
          dockerfile: Dockerfile
        image: phoenix741/passprotect-server:develop
        ports:
            - 4000:4000
        links:
            - mongodb
        environment:
            - NODE_ENV=development
            - MONGODB_HOST=mongodb://mongodb:27017
            - MONGODB_DATABASE=passprotect
            - JWT_SECRET=dnLUMtULQsNmNbmGV3Lx8SxrxEtaxTc8aPdRh8YMemj515Faip7wQYueSaBFYm5r
            - ENGINE_API_KEY=service:passprotect:MXL3nFT4FbnEkWgMPkmYkQ
            - ENGINE_SCHEMA_TAG=dev
    mongodb:
        image: mongo:4
        ports:
            - '27017:27017'
        volumes:
            - './mongodb:/data'
