query getLineById($id: ID!) {
  line(id: $id) {
    _id
    type
    label
		group
    encryption {
      salt
      informations {
        content
        authTag
      }
    }
    updatedAt
    _rev
  }
}
