config:
    mongodb:
        host: MONGODB_HOST
        database: MONGODB_DATABASE
        user: MONGODB_USER
        password: MONGODB_PASSWORD
        options: MONGODB_OPTIONS

    jwt:
        secret: JWT_SECRET

