config:
    mongodb:
        host: ~
        user: ~
        password: ~
        options: ~

    jwt:
        secret: 'dnLUMtULQsNmNbmGV3Lx8SxrxEtaxTc8aPdRh8YMemj515Faip7wQYueSaBFYm5r'

    client:
        crypto:
            pbkdf2:
                iterations: 1000
                keylen: 256
                ivlen: 96
                digest: sha512
            cypherIv:
                algorithm: 'AES-256-GCM'
            ivSize: 64
            keySize: 256
