config:
    mongodb:
        host: ~
        database: ~
        user: ~
        password: ~
        options: ~

    jwt:
        secret: 'dnLUMtULQsNmNbmGV3Lx8SxrxEtaxTc8aPdRh8YMemj515Faip7wQYueSaBFYm5r'
